### ISSUE TITLE
auslesen der settings

### ISSUE THREAD

**Issue by isospin** [studio-ahoi/ahoi_backend_form#1]
hallo daniel,
kannst du mir einen kurzen tip geben, wie  ich die variablen in einem template wieder auslese?
vielen dank
ingo

**Comment by DanielWeitenauer** [comment]
Hallo Ingo,

Da gibt es verschiedene Wege, je nachdem, wo Du die Settings haben möchtest:

Du lädst sie über die Settings Class z.B. im Addon, dann werden sie im $REX Array bereitgestellt:
```php
$obj = new ahoi\Form\Config\Settings($addon_name);
$obj->loadSettings();
```

Du lädst sie über die Settings Class, nutzt aber einfach den Rückgabewert der Methode, sie sind dann allerdings trotzdem auch im $REX Array vorhanden:
```php
$obj = new ahoi\Form\Config\Settings($addon_name);
$settings = $obj->loadSettings();
```

Du includest einfach die Settings-Datei, dann liegen sie danach in der Variable $settings - sie sollte also nicht für irgend etwas anderes genutzt worden sein.
```php
include ($REX['INCLUDE_PATH'].'/data/addons/addon_name/settings.inc.php); 
```

Die Klasse findest Du hier: https://github.com/studio-ahoi/ahoi_backend_form/blob/master/lib/Form/Config/Settings.php, sie enthält auch Methoden, um den Dateinamen und den Pfad zu ändern.

Viele Grüße,
Daniel
